# version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:  # ✅ Load variables from .env
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
